export const KAPSULA_ANIMATION = {
  heroReveal: {
    selectors: {
      hero: "[data-kapsula-hero]",
      content: "[data-kapsula-content]",
      eyebrow: ".kapsula__eyebrow",
      title: ".kapsula-copy__title",
      subtitle: ".kapsula-copy__subtitle",
      startButton: ".kapsula-button--hero",
      backdrop: ".kapsula__backdrop",
    },
    initial: {
      contentY: 28,
      backdropScale: 1.08,
    },
    timeline: {
      defaults: {
        ease: "power3.out",
      },
      backdrop: {
        scale: 1.02,
        duration: 1.8,
        ease: "power2.out",
      },
      eyebrow: {
        autoAlpha: 1,
        y: 0,
        duration: 0.5,
        at: "-=1.15",
      },
      title: {
        autoAlpha: 1,
        y: 0,
        duration: 0.75,
        at: "-=0.18",
      },
      subtitle: {
        autoAlpha: 1,
        y: 0,
        duration: 0.6,
        at: "-=0.42",
      },
      startButton: {
        autoAlpha: 1,
        y: 0,
        duration: 0.5,
        at: "-=0.32",
      },
    },
  },
  screenTransition: {
    selectors: {
      heroScreen: '[data-kapsula-screen="hero"]',
      stepsScreen: '[data-kapsula-screen="steps"]',
      stylesScreen: '[data-kapsula-screen="styles"]',
      formScreen: '[data-kapsula-screen="form"]',
      stepsTitle: '[data-kapsula-screen="steps"] .kapsula-copy__title',
      stepsCards: ".kapsula-step-card",
      stepsNote: ".kapsula-steps__note",
      stepsButton: ".kapsula-button--steps",
      stepsProgress: ".kapsula-progress",
      stylesTitle: '[data-kapsula-screen="styles"] .kapsula-copy__title',
      styleCards: ".kapsula-style-card",
      styleCardButtons: ".kapsula-style-card .kapsula-button",
      formTitle: '[data-kapsula-screen="form"] [data-kapsula-form-title]',
      formSubtitle: '[data-kapsula-screen="form"] [data-kapsula-form-subtitle]',
      formAside: '[data-kapsula-screen="form"] .kapsula-form-screen__aside',
      formBody: '[data-kapsula-screen="form"] [data-kapsula-form]',
      progressItem: "[data-kapsula-progress-item]",
      progressButton: "[data-kapsula-progress-target]",
    },
    initial: {
      y: 24,
      heroOutY: -18,
    },
    timeline: {
      defaults: {
        ease: "power3.out",
      },
      heroScreen: {
        opacity: 0,
        y: -18,
        duration: 0.45,
      },
      stepsScreen: {
        opacity: 1,
        duration: 0.2,
        at: "-=0.08",
      },
      stepsTitle: {
        autoAlpha: 1,
        y: 0,
        duration: 0.6,
        at: "-=0.02",
      },
      stepsCards: {
        autoAlpha: 1,
        y: 0,
        duration: 0.55,
        stagger: 0.08,
        at: "-=0.28",
      },
      stepsNote: {
        autoAlpha: 1,
        y: 0,
        duration: 0.45,
        at: "-=0.2",
      },
      stepsButton: {
        autoAlpha: 1,
        y: 0,
        duration: 0.45,
        at: "-=0.18",
      },
      stepsProgress: {
        autoAlpha: 1,
        y: 0,
        duration: 0.45,
        at: "-=0.18",
      },
      stylesScreen: {
        opacity: 1,
        duration: 0.2,
        at: "-=0.06",
      },
      stylesTitle: {
        autoAlpha: 1,
        y: 0,
        duration: 0.6,
        at: "-=0.02",
      },
      styleCards: {
        autoAlpha: 1,
        y: 0,
        duration: 0.55,
        stagger: 0.08,
        at: "-=0.24",
      },
      formScreen: {
        opacity: 1,
        duration: 0.2,
        at: "-=0.06",
      },
      formTitle: {
        autoAlpha: 1,
        y: 0,
        duration: 0.6,
        at: "-=0.02",
      },
      formSubtitle: {
        autoAlpha: 1,
        y: 0,
        duration: 0.45,
        at: "-=0.22",
      },
      formAside: {
        autoAlpha: 1,
        y: 0,
        duration: 0.55,
        at: "-=0.18",
      },
      formBody: {
        autoAlpha: 1,
        y: 0,
        duration: 0.5,
        at: "-=0.16",
      },
    },
  },
};
